export enum Collections {
  LEADS = 'leads',
  USERS = 'users',
  PROVIDERS = 'providers',
  PRODUCTS = 'products',
  PACKAGES = 'packages',
  STAFF = 'staff',
  ASPECTS = 'aspects',
  LEVELS = 'levels',
  TASKS = 'tasks',
  USER_TASKS = 'userTasks',
  USER_TASKS_HISTORY = 'userTasksHistory',
  USER_TOUCHPOINTS = 'userTouchpoints',

  ATTACHMENTS = 'attachments',
  USERS_BY_STAFF = 'usersByStaff',
  PROGRESS_OPTIONS = 'progressOptions',
  HOOKED_EVENTS = 'hookedEvents',
  USER_DYNAMIC_ATTRIBUTES = 'userDynamicAttributes',
  USER_ATTRIBUTES_TYPES = 'userAttributesTypes',
  USER_PRODUCTS = 'userProducts',
  USER_WELL_BEING_ATTRIBUTES = 'userWellBeingAttributes',
  OAUTH2_TOKENS = 'oauth2Tokens',
  USER_CALENDARS = 'userCalendars',
  USER_CALENDAR_EVENTS = 'userCalendarEvents',
  COMPANIES = 'companies',
  COMPANY_EMPLOYEES = 'companyEmployees',
  COMPANY_CLIENTS = 'companyClients',
  COMPANY_PROFILES = 'companyProfiles',
  COMPANY_DEPARTMENTS = 'companyDepartments',

  VAULTS = 'vaults',
  VAULT_INSTALLMENTS = 'vaultInstallments',
  VAULT_TRANSACTIONS = 'vaultTransactions',
  TRANSACTION_REQUESTS = 'transactionRequests',
}
