# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: On tag created - Firebase deploy QA

on:
  push:
    branches:
      - catedral
    tags:
      - rc*

env:
  SYS_ADMIN_EMAIL: 'manuel@aconcagua.finance'

  TEST_ENV_KEY: 'TEST_ENV_VALUE'
  ENVIRONMENT: qa

  FIREB_PROJECT_ID: 'catedral-fb'
  FIREB_API_KEY: 'AIzaSyDTA7zMmjRD1L95x96s4r0WM9-JrDNNe_0'
  FIREB_AUTH_DOMAIN: 'catedral-fb.firebaseapp.com'
  FIREB_STORAGE_BUCKET: 'catedral-fb.appspot.com'
  FIREB_MESSAGING_SENDER_ID: 428867726479
  FIREB_APP_ID: '1:428867726479:web:ec0059f93c8b01b65354fa'
  FIREB_MEASURAMENT_ID: 'G-LKFV3L66D3'

  DEPLOYER_PRIVATE_KEY: ${{secrets.DEPLOYER_PRIVATE_KEY_QA}}
  SWAPPER_PRIVATE_KEY: ${{secrets.SWAPPER_PRIVATE_KEY_QA}}
  ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY_QA}}
  HARDHAT_API_URL: ${{secrets.ALCHEMY_API_URL_QA}}
  HARDHAT_NETWORK_NAME: 'sepolia'
  PROVIDER_NETWORK_NAME: 'sepolia'
  POLYGONSCAN_API_KEY: ${{secrets.POLYGONSCAN_API_KEY_QA}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY_QA}}

  USDC_TOKEN_ADDRESS: '0xdf8d9E002533Cd7A2dDc5380764560328661Ae71'
  USDT_TOKEN_ADDRESS: '0x02B1d825d3ff7A3CC51C3d3Df5A8de749DF609AE'
  USDM_TOKEN_ADDRESS: '0xD88b19F80933B9Bc06406274a421FF8cE3bdb697'
  WBTC_TOKEN_ADDRESS: '0x1E94bc717D52B5F8aEEB40f4E74687a3fd34c38f'

  #WETH_TOKEN_ADDRESS: '0xdf8d9E002533Cd7A2dDc5380764560328661Ae71'

  QUOTER2_CONTRACT_ADDRESS: '0x61fFE014bA17989E743c5F6cB21bF9697530B21e'
  SWAP_ROUTER_V3_ADDRESS: '0xE592427A0AEce92De3Edee1F18E0157C05861564'

  SWAPPER_ADDRESS: '0x0E8adC0975290Bb90A9fFC136A02C4721FbC371F'
  OPERATOR1_ADDRESS: '0x3Fd92265C0ee6790488Ff59c6c44bd8a1d593956' # Acon Operator 1 (deployer was used for transition)
  OPERATOR2_ADDRESS: '0x0f4F62173dBf207B6AcDB7e0AD88643c4e4d124F' # Acon Operator 2
  OPERATOR3_ADDRESS: '0xB4A89eE37F0f9abAA628b2a097469fd85898491D' # Acon Operator 3
  DEFAULT_RESCUE_WALLET_ADDRESS: '0x0c8060812F614B70E2cF3a9CD3fC0333453eE0A6'
  DEFAULT_WITHDRAW_WALLET_ADDRESS: '0x2C1747a1101355e5FfA54F597965152079DE78F2'

  # Mumbai Safe account creation (QA only): Acon defaults
  ALIQ1_ADDRESS: '0xBC747d69e7cA913dFCC988722e84972139e92921'
  ALIQ2_ADDRESS: '0x3D49Dd4754d121E52d1a9278Df5CBf19eD4625a4'

  GAS_STATION_URL: 'https://gasstation-mumbai.matic.today/v2'
  COINGECKO_URL: 'https://api.coingecko.com/api/v3'
  BINANCE_URL: 'https://data.binance.com/api/v3'
  API_PATH_QUOTES: 'http://us-central1-catedral-fb.cloudfunctions.net/market/pathQuotes'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.19.0
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          # NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} este no tiee permisos en otro repo
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
      - run: npm run prettier-ci
      - run: npm run lint-ci
      - run: npm run test-ci

      # ya lo hace el firebase.json
      # - run: npm run build

      - run: npm run deploy-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY_QA}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci

  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
