# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: On tag created - Firebase deploy Sandbox

on:
  push:
    tags:
      - sb*

env:
  SYS_ADMIN_EMAIL: 'pruebas@aconcagua.finance'

  TEST_ENV_KEY: 'TEST_ENV_VALUE'
  ENVIRONMENT: sandbox

  FIREB_PROJECT_ID: 'lanin-6339b'
  FIREB_API_KEY: 'AIzaSyBekTDESxGgAx9EVMOfkHhvaKyA8p9rLeg'
  FIREB_AUTH_DOMAIN: 'lanin-6339b.firebaseapp.com'
  FIREB_STORAGE_BUCKET: 'lanin-6339b.appspot.com'
  FIREB_MESSAGING_SENDER_ID: 371212123512
  FIREB_APP_ID: '1:371212123512:web:c4b0fde885caa45036dc8d'
  FIREB_MEASURAMENT_ID: 'G-7X16DSM5BJ'

  # Default variables for Sepolia network
  DEPLOYER_PRIVATE_KEY_POLYGON: ${{secrets.DEPLOYER_PRIVATE_KEY_SB}}
  DEPLOYER_PRIVATE_KEY_ROOTSTOCK: ${{secrets.DEPLOYER_PRIVATE_KEY_SB_ROOTSTOCK}}
  SWAPPER_PRIVATE_KEY: ${{secrets.SWAPPER_PRIVATE_KEY_SB}}
  HARDHAT_API_URL: ${{secrets.ALCHEMY_API_URL_SB}}
  HARDHAT_NETWORK_NAME: sepolia
  PROVIDER_NETWORK_NAME: sepolia
  POLYGONSCAN_API_KEY: ${{secrets.POLYGONSCAN_API_KEY_SB}}
  CONFIG_NETWORK_COLLECTION: 'configNetworks'

  COINGECKO_URL: 'https://api.coingecko.com/api/v3'
  BINANCE_URL: 'https://api.binance.com/api/v3'
  KRAKEN_URL: 'https://api.kraken.com/0/public'
  API_PATH_QUOTES: 'http://us-central1-lanin-6339b.cloudfunctions.net/market/pathQuotes'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.19.0
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force --legacy-peer-deps
      - run: npm run prettier-ci
      - run: npm run lint-ci
      - run: npm run test-ci
        env:
          DEPLOYER_PRIVATE_KEY: ${{secrets.SWAPPER_PRIVATE_KEY_SB}}
          HARDHAT_API_URL: ${{secrets.ALCHEMY_API_URL_SB}}
          HARDHAT_NETWORK_NAME: sepolia

      # ya lo hace el firebase.json
      # - run: npm run build

      - run: npm run deploy-ci
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY_SB}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci

  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
