# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: On release created - Firebase deploy PROD

on:
  release:
    types: [published]

# on:
#   push:
#     tags:
#       - v*

env:
  SYS_ADMIN_EMAIL: 'manuel@aconcagua.finance'

  TEST_ENV_KEY: 'TEST_ENV_VALUE'
  ENVIRONMENT: prod

  DEPLOYER_PRIVATE_KEY_POLYGON: ${{secrets.DEPLOYER_PRIVATE_KEY_PROD}}
  DEPLOYER_PRIVATE_KEY_ROOTSTOCK: ${{secrets.DEPLOYER_PRIVATE_KEY_PROD_ROOTSTOCK}}
  SWAPPER_PRIVATE_KEY_POLYGON: ${{secrets.SWAPPER_PRIVATE_KEY_PROD}}
  SWAPPER_PRIVATE_KEY_ROOTSTOCK: ${{secrets.SWAPPER_PRIVATE_KEY_PROD_ROOTSTOCK}}
  HARDHAT_API_URL: ${{secrets.ALCHEMY_API_URL_PROD}}
  HARDHAT_NETWORK_NAME: 'matic'
  PROVIDER_NETWORK_NAME: 'matic'
  POLYGONSCAN_API_KEY: ${{secrets.POLYGONSCAN_API_KEY_PROD}}
  CONFIG_NETWORK_COLLECTION: 'configNetworks'

  COINGECKO_URL: 'https://api.coingecko.com/api/v3'
  BINANCE_URL: 'https://api.binance.com/api/v3'
  KRAKEN_URL: 'https://api.kraken.com/0/public'
  API_PATH_QUOTES: 'http://us-central1-aconcagua-365314.cloudfunctions.net/market/pathQuotes'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.19.0
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force --legacy-peer-deps
      - run: npm run prettier-ci
      - run: npm run lint-ci
      - run: npm run test-ci
        env:
          DEPLOYER_PRIVATE_KEY: ${{secrets.SWAPPER_PRIVATE_KEY}}
          HARDHAT_API_URL: ${{secrets.ALCHEMY_API_URL}}
          HARDHAT_NETWORK_NAME: matic

      # ya lo hace el firebase.json
      # - run: npm run build

      - run: npm run deploy-ci
        env:
          FIREB_PROJECT_ID: 'aconcaguapsav'
          FIREB_API_KEY: 'AIzaSyDygVepLEVhHVnzVTwMOtbhOEvPg_hI6w4'
          FIREB_AUTH_DOMAIN: 'aconcaguapsav.firebaseapp.com'
          FIREB_STORAGE_BUCKET: 'aconcaguapsav.appspot.com'
          FIREB_MESSAGING_SENDER_ID: 860753192899
          FIREB_APP_ID: '1:860753192899:web:85929d7f0577a55be37f76'
          FIREB_MEASURAMENT_ID: 'G-46L2Y66TPG'

          FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY_PSAV}}

          # DEFAULT_RESCUE_WALLET_ADDRESS: '0xF28a754746C49ceB19B9549a3C173EEA2dA66E27'
          # DEFAULT_WITHDRAW_WALLET_ADDRESS: '0x333Bc1bE5805CABB3a1cB1fcb37Ba36aEDA65b97'

      - run: npm run deploy-ci
        env:
          FIREB_PROJECT_ID: 'aconcagua-365314'
          FIREB_API_KEY: 'AIzaSyCVjVkwUc63D9ES6AVwPCEahJHw1ky978Q'
          FIREB_AUTH_DOMAIN: 'aconcagua-365314.firebaseapp.com'
          FIREB_STORAGE_BUCKET: 'aconcagua-365314.appspot.com'
          FIREB_MESSAGING_SENDER_ID: 101110014661
          FIREB_APP_ID: '1:101110014661:web:137167add231676d4846ac'
          FIREB_MEASURAMENT_ID: 'G-4EP13854VS'

          FIREBASE_SERVICE_ACCOUNT_KEY: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY}}
          FIREBASE_SERVICE_ACCOUNT_KEY_PSAV: ${{secrets.FIREBASE_SERVICE_ACCOUNT_KEY_PSAV}}

          # DEFAULT_RESCUE_WALLET_ADDRESS: '0x9c6AA3435528d7476a672E557458559FBE3C08D2'
          # DEFAULT_WITHDRAW_WALLET_ADDRESS: '0xEb870025A934fcE1eF7a8873c660ccC6B0cDc71d'

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci

  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
