# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: On tag created - Firebase deploy QA

on:
  push:
    tags:
      - rc*

env:
  SYS_ADMIN_EMAIL: 'manuel@aconcagua.finance'

  TEST_ENV_KEY: 'TEST_ENV_VALUE'
  ENVIRONMENT: qa

  FIREB_PROJECT_ID: 'catedral-fb'
  FIREB_API_KEY: 'AIzaSyDTA7zMmjRD1L95x96s4r0WM9-JrDNNe_0'
  FIREB_AUTH_DOMAIN: 'catedral-fb.firebaseapp.com'
  FIREB_STORAGE_BUCKET: 'catedral-fb.appspot.com'
  FIREB_MESSAGING_SENDER_ID: 428867726479
  FIREB_APP_ID: '1:428867726479:web:ec0059f93c8b01b65354fa'
  FIREB_MEASURAMENT_ID: 'G-LKFV3L66D3'

  WALLET_PRIVATE_KEY: ${{secrets.WALLET_PRIVATE_KEY_QA}}
  ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY_QA}}
  HARDHAT_API_URL: ${{secrets.ALCHEMY_API_URL_QA}}
  HARDHAT_NETWORK_NAME: 'mumbai'
  PROVIDER_NETWORK_NAME: 'maticmum'
  POLYGONSCAN_API_KEY: ${{secrets.POLYGONSCAN_API_KEY_QA}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY_QA}}
  USDC_TOKEN_ADDRESS: '0x8f924e4acc9000102bfF654c34a1B0ee2aFc737A'
  USDT_TOKEN_ADDRESS: '0xA02f6adc7926efeBBd59Fd43A84f4E0c0c91e832'
  WBTC_TOKEN_ADDRESS: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889'
  WETH_TOKEN_ADDRESS: '0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa'
  GAS_STATION_URL: 'https://gasstation-mumbai.matic.today/v2'
  COINGECKO_URL: 'https://api.coingecko.com/api/v3'
  BINANCE_URL: 'https://data.binance.com/api/v3'
  QUOTER2_CONTRACT_ADDRESS: '0x61fFE014bA17989E743c5F6cB21bF9697530B21e'
  SWAP_ROUTER_V3_ADDRESS: '0xE592427A0AEce92De3Edee1F18E0157C05861564'
  API_PATH_QUOTES: 'http://us-central1-aconcagua-365314.cloudfunctions.net/market/pathQuotes'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.1
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          # NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} este no tiee permisos en otro repo
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
      - run: npm run prettier-ci
      - run: npm run lint-ci
      - run: npm run test-ci

      # ya lo hace el firebase.json
      # - run: npm run build

      - run: npm run deploy-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci

  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
