# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: On release created - Firebase deploy PROD

on:
  release:
    types: [published]

# on:
#   push:
#     tags:
#       - v*

env:
  SYS_ADMIN_EMAIL: 'manuel@aconcagua.finance'

  TEST_ENV_KEY: 'TEST_ENV_VALUE'
  ENVIRONMENT: prod

  FIREB_PROJECT_ID: 'aconcagua-365314'
  FIREB_API_KEY: 'AIzaSyCVjVkwUc63D9ES6AVwPCEahJHw1ky978Q'
  FIREB_AUTH_DOMAIN: 'aconcagua-365314.firebaseapp.com'
  FIREB_STORAGE_BUCKET: 'aconcagua-365314.appspot.com'
  FIREB_MESSAGING_SENDER_ID: 101110014661
  FIREB_APP_ID: '1:101110014661:web:137167add231676d4846ac'
  FIREB_MEASURAMENT_ID: 'G-4EP13854VS'

  WALLET_PRIVATE_KEY: ${{secrets.WALLET_PRIVATE_KEY_PROD}}
  ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY_PROD}}
  HARDHAT_API_URL: ${{secrets.ALCHEMY_API_URL_PROD}}
  HARDHAT_NETWORK_NAME: 'matic'
  PROVIDER_NETWORK_NAME: 'matic'
  POLYGONSCAN_API_KEY: ${{secrets.POLYGONSCAN_API_KEY_PROD}}
  ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY_PROD}}
  USDC_TOKEN_ADDRESS: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174'
  USDT_TOKEN_ADDRESS: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f'
  WBTC_TOKEN_ADDRESS: '0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6'
  WETH_TOKEN_ADDRESS: '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619'
  GAS_STATION_URL: 'https://gasstation-mainnet.matic.network/v2'
  COINGECKO_URL: 'https://api.coingecko.com/api/v3'
  BINANCE_URL: 'https://data.binance.com/api/v3'
  API_PATH_QUOTES: 'http://us-central1-aconcagua-365314.cloudfunctions.net/market/pathQuotes'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.1
          registry-url: https://npm.pkg.github.com/
      - run: npm ci --force --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          # NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} este no tiee permisos en otro repo
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
      - run: npm run prettier-ci
      - run: npm run lint-ci
      - run: npm run test-ci

      # ya lo hace el firebase.json
      # - run: npm run build

      - run: npm run deploy-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          VS_GITHUB_NPM_TOKEN: ${{secrets.VS_GITHUB_NPM_TOKEN}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci

  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
